services:
  trans_backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../fontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p trans_full up -d
  